const COOKIE_NAMES = {
  REFRESH_TOKEN: 'refreshToken',
  ACCESS_TOKEN: 'idToken',
  USERNAME: 'username',
  USER_ID: 'userId',
  CRYPT_ID: 'cryptID',
};

const LABEL_TYPOGRAPHY_HEIGHT = 50;
const LABEL_TYPOGRAPHY_MARGIN_BOT = 16;

export { COOKIE_NAMES, LABEL_TYPOGRAPHY_HEIGHT, LABEL_TYPOGRAPHY_MARGIN_BOT };
